/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleProofSol from "./merkleProof.sol";
export type { merkleProofSol };
import type * as tokenSol from "./token.sol";
export type { tokenSol };
import type * as tokenDistSol from "./tokenDist.sol";
export type { tokenDistSol };
